# Generated by Django 3.1.7 on 2021-03-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photoUsers', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='tutors',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photoTutors', verbose_name='Фотография'),
        ),
    ]
