# Generated by Django 3.1.7 on 2021-03-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_auto_20210303_0103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='tutors',
            name='phone_number',
            field=models.TextField(blank=True, null=True, verbose_name='Мобильный телефон'),
        ),
    ]
