# Generated by Django 3.1.7 on 2021-03-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_auto_20210303_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='lesson',
            field=models.ManyToManyField(blank=True, null=True, related_name='tutors', to='testing.Lesson', verbose_name='Предметы'),
        ),
    ]
