# Generated by Django 3.1.4 on 2021-03-03 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_auto_20210303_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='basic',
            field=models.BooleanField(default=False, verbose_name='Основной предмет'),
        ),
    ]
