# Generated by Django 3.1.4 on 2021-03-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_lesson_countquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pages',
            name='basic',
            field=models.BooleanField(default=False, verbose_name='Главная'),
        ),
    ]
