# Generated by Django 3.1.4 on 2021-03-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_pages_basic'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Код теста'),
        ),
    ]
