# Generated by Django 3.1.4 on 2021-03-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0010_auto_20210304_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterField(
            model_name='code',
            name='number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
