# Generated by Django 3.1.7 on 2021-03-08 09:08

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_auto_20210304_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
