# Generated by Django 3.1.7 on 2021-03-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0014_auto_20210315_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка'),
        ),
    ]
