# Generated by Django 3.1.7 on 2021-03-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0015_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_kk',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='pages',
            name='content_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Контент'),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='pages',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
