# Generated by Django 3.1.7 on 2021-03-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0016_auto_20210321_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
