# Generated by Django 3.1.7 on 2021-03-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0018_profile_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertests',
            options={'ordering': ['-date'], 'verbose_name': 'Тест пользователя', 'verbose_name_plural': 'Тесты пользователей'},
        ),
        migrations.AddField(
            model_name='question',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='question_img'),
        ),
    ]
