# Generated by Django 3.1.7 on 2021-04-03 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0021_codegroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroups',
            name='user',
            field=models.ManyToManyField(related_name='userGroups', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
