# Generated by Django 3.1.7 on 2021-04-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0022_auto_20210403_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroups',
            old_name='user',
            new_name='users',
        ),
    ]
