# Generated by Django 3.1.7 on 2021-04-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0023_auto_20210404_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='codegroups',
            name='dateEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='codegroups',
            name='dateStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
