# Generated by Django 3.1.7 on 2021-04-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0024_auto_20210404_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='code',
            options={'verbose_name': 'Код', 'verbose_name_plural': 'Коды'},
        ),
        migrations.AddField(
            model_name='profile',
            name='lesson',
            field=models.ManyToManyField(related_name='users', to='testing.Lesson'),
        ),
    ]
