# Generated by Django 3.1.7 on 2021-04-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0026_auto_20210404_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='basic',
            new_name='trial',
        ),
    ]
