# Generated by Django 3.1.7 on 2021-04-04 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testing', '0027_auto_20210404_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='codegroups',
            name='users',
            field=models.ManyToManyField(related_name='codeGroups', to=settings.AUTH_USER_MODEL),
        ),
    ]
