# Generated by Django 3.1.7 on 2021-04-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0029_auto_20210404_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_kk',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='role',
            name='name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
