# Generated by Django 3.1.7 on 2021-04-06 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0031_auto_20210404_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codegroups',
            name='users',
        ),
    ]
